# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DytUu7XFEOJkpD_B7zqOdrvaOTN7LNFo
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([1, 2, 6, 8])
y = np.array([3, 8, 1, 10])


plt.plot(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


t = np.linspace(0, 2 * np.pi, 1000)


x = 16 * np.sin(t)**3
y = 13 * np.cos(t) - 5 * np.cos(2*t) - 2 * np.cos(3*t) - np.cos(4*t)

plt.plot(x, y, color="blue")
plt.fill(x, y, color="blue", alpha=0.6)
plt.title("Heart Shape")
plt.axis('equal')
plt.show()



import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

def heart_shape(t, scale=1):
    x = scale * 16 * np.sin(t)**3
    y = scale * (13 * np.cos(t) - 5 * np.cos(2*t) - 2 * np.cos(3*t) - np.cos(4*t))
    return x, y

t = np.linspace(0, 2 * np.pi, 1000)

fig, ax = plt.subplots()
ax.set_xlim(-20, 20)
ax.set_ylim(-20, 20)
ax.set_aspect('equal')

ax.set_title("Pumping Heart")


def update(frame):
    ax.clear()
    ax.set_xlim(-20, 20)
    ax.set_ylim(-20, 20)
    ax.set_aspect('equal')


    scale = 1 + 0.2 * np.sin(frame * 0.1)
    x, y = heart_shape(t, scale)

    ax.plot(x, y, color="red", linewidth=2)


ani = FuncAnimation(fig, update, frames=np.arange(0, 200), interval=50)

HTML(ani.to_jshtml())

import matplotlib.pyplot as plt
import numpy as np

y = np.array([3, 8, 1, 10])

plt.plot(y, marker='o', ms = 20, mec = 'r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1 = np.array([0, 1, 2, 3])
y1 = np.array([3, 8, 1, 10])
x2 = np.array([0, 1, 2, 3])
y2 = np.array([6, 2, 7, 11])

plt.plot(x1, y1, x2, y1)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([0, 8, 12, 20, 26, 38])

plt.scatter(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([0, 2, 8, 1, 14, 7])
plt.scatter(x, y, color = 'red')

x = np.array([12, 6, 8, 11, 8, 3])
y = np.array([5, 6, 3, 7, 17, 19])
plt.scatter(x, y, color='green')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 1, 2, 3, 4, 5])
y = np.array([0, 2, 8, 1, 14, 7])
mycolor = ['red', 'green', 'purple', 'lime', 'aqua', 'yellow']

plt.scatter(x, y, color= mycolor)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 1, 2, 3, 4,5])
y = np.array([0, 2, 8, 1, 14, 7])
mycolor = ['red', 'green', 'purple', 'lime', 'aqua', 'yellow']

size = [10, 60, 120, 80, 20, 190]
plt.scatter(x, y, color= mycolor, s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(['A', 'B', 'C', 'D'])
y= np.array([3, 8, 1, 10])

plt.bar(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(['A', 'B', 'C', 'D'])
y= np.array([3, 8, 1, 10])

plt.barh(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([35, 25, 25, 15])

plt.pie(x)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([35, 25, 25, 15])

mylabels = ["Apples", "Bananas", "Cherries", "Dates"]

plt.pie(x, labels = mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([35, 25, 25, 15])

mylabels = ["Apples", "Bananas", "Cherries", "Dates"]

plt.pie(x, labels = mylabels, startangle = 90)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([35, 25, 25, 15])

mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode = [0, 2, 0, 0]

plt.pie(y, labels = mylabels, startangle=90, explode = myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([35, 25, 25, 15])

mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode = [0, 2, 0, 0]

plt.pie(x, labels = mylabels, startangle=90, explode = myexplode, shadow = True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([35, 25, 25, 15])

mycolors = ["black", 'hotpink', 'b', '#4CAF50']
mylabels = ["Apples", "Bananas", "Cherries", "Dates"]
myexplode = [0, 2, 0, 0]

plt.pie(x, labels = mylabels, startangle=90, explode = myexplode,colors=mycolors)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([35, 25, 25, 15])

mylabels = ["Apples", "Bananas", "Cherries", "Dates"]

plt.pie(x, labels = mylabels)
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([35, 25, 25, 15])

mylabels = ["Apples", "Bananas", "Cherries", "Dates"]

plt.pie(x, labels = mylabels)
plt.legend(title = 'Four Fruits: ')
plt.show()